### ISSUE TITLE
attribute-completeness: figure shows wrong label

### ISSUE THREAD

**Issue by Gigaszi** [GIScience/ohsome-quality-api#811]
![image](https://github.com/user-attachments/assets/348c88fd-32fb-4acc-bae9-671d3593bcd3)

**Comment by JanReifenrath** [comment]
The label of medium completeness is correct in this case, as values until 75% are labeled as medium completeness (yellow). The problem here is with the arrow pointing to the wrong value depending on the zoom of the plot. This problem has been fixed now and both the label and the bar are accurate now.

**Comment by JanReifenrath** [comment]
The label of medium completeness is correct in this case, as values until 75% are labeled as medium completeness (yellow). The problem here is with the arrow pointing to the wrong value depending on the zoom of the plot. This problem has been fixed now and both the label and the bar are accurate now.
